dependencies:
  - name: mongodb
    # Versions above 7.8 (<7.10.2) contains an error 
    version: "> 7.10.2"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: postgresql
    version: ">= 0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
